name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Install dojo
        run: |
          wget -O /usr/bin/dojo https://github.com/kudulab/dojo/releases/download/0.11.0/dojo_linux_amd64
          chmod +x /usr/bin/dojo
      -
        name: Test
        run: |
          echo "DOJO_DOCKER_IMAGE=\"${{ env.TEST_TAG }\"" > ./Dojofile.to_be_tested
          echo "DOJO_IDENTITY_OUTER=./test/integration/identities/full" >> ./Dojofile.to_be_tested
          echo "DOJO_WORK_OUTER=./test/integration/test_dojo_work" >> ./Dojofile.to_be_tested
          dojo -c ./Dojofile.to_be_tested "time bats /opt/self-test"
          # docker run --rm ${{ env.TEST_TAG }} bats /opt/self-test
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64
          push: true
          tags: kiefm/spin-dojo-image-base:latest
